plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.github.appuraja1.cropper'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdk rootProject.ext.minSdkVersion
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
       // consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    publishing {
        singleVariant('release') {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.2'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.appuraja1'
                artifactId = 'cropper'
                version = '1.0.2'
            }
        }
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/appuraja1/Android-Image-Cropper")
                credentials {
                    username = System.getenv("GITHUB_ACTOR")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}