plugins {
    id 'com.android.application'
}

android {
    namespace 'com.github.appuraja1.cropper.sample'
    compileSdk rootProject.ext.compileSdkVersion

    defaultConfig {
        applicationId "com.github.appuraja1.cropper.sample"
        minSdk rootProject.ext.minSdkVersion
        targetSdk rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation project(':cropper')
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation 'com.google.android.material:material:1.14.0'
}